"""users upgrated

Revision ID: e0b9ea844ed7
Revises: be131e775b02
Create Date: 2026-05-24 16:38:52.790917

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e0b9ea844ed7"
down_revision: Union[str, Sequence[str], None] = "be131e775b02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users", "password", existing_type=postgresql.BYTEA(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", existing_type=postgresql.BYTEA(), nullable=True)
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
