"""add user auth fields

Revision ID: be131e775b02
Revises: cefff8762258
Create Date: 2026-05-24 11:48:02.731799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "be131e775b02"
down_revision: Union[str, Sequence[str], None] = "cefff8762258"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("password", sa.LargeBinary(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.execute("UPDATE users SET password = ''::bytea WHERE password IS NULL")
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=55), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=55), nullable=True
    )
    op.drop_column("users", "is_active")
    op.drop_column("users", "password")
    op.drop_column("users", "email")
    # ### end Alembic commands ###
